apiVersion: apps/v1
kind: Deployment
metadata:
  name: workshop-service
  labels:
    app.kubernetes.io/name: workshop-service
    app.kubernetes.io/part-of: fiap-tech-challenge
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: workshop-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: workshop-service
        app.kubernetes.io/part-of: fiap-tech-challenge
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "3000"
    spec:
      initContainers:
        - name: run-migrations
          image: ghcr.io/replace-me/workshop-service:latest
          imagePullPolicy: IfNotPresent
          command: ["npm", "run", "migration:run:prod"]
          envFrom:
            - configMapRef:
                name: workshop-service-config
            - secretRef:
                name: workshop-service-secret
          env:
            - name: RABBITMQ_URL
              valueFrom:
                secretKeyRef:
                  name: platform-rabbitmq-connection
                  key: RABBITMQ_URL
      containers:
        - name: workshop-service
          image: ghcr.io/replace-me/workshop-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 3000
          envFrom:
            - configMapRef:
                name: workshop-service-config
            - secretRef:
                name: workshop-service-secret
          env:
            - name: RABBITMQ_URL
              valueFrom:
                secretKeyRef:
                  name: platform-rabbitmq-connection
                  key: RABBITMQ_URL
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 20
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 3
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
