apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: workshop-service
  labels:
    app.kubernetes.io/name: workshop-service
    app.kubernetes.io/part-of: fiap-tech-challenge
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: workshop-service
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
