apiVersion: v1
kind: Secret
metadata:
  name: workshop-service-secret
  labels:
    app.kubernetes.io/name: workshop-service
    app.kubernetes.io/part-of: fiap-tech-challenge
type: Opaque
stringData:
  JWT_SECRET: "replace-with-auth-function-jwt-secret"
  DB_USERNAME: "replace-with-managed-mysql-username"
  DB_PASSWORD: "replace-with-managed-mysql-password"
