apiVersion: v1
kind: Secret
metadata:
  name: workshop-service-secret
  labels:
    app.kubernetes.io/name: workshop-service
    app.kubernetes.io/part-of: fiap-tech-challenge
type: Opaque
stringData:
  JWT_SECRET: "${JWT_SECRET}"
  DB_USERNAME: "${WORKSHOP_DB_USERNAME}"
  DB_PASSWORD: "${WORKSHOP_DB_PASSWORD}"
