export const PART_REPOSITORY = Symbol("PART_REPOSITORY");
export const STOCK_RESERVATION_REPOSITORY = Symbol(
  "STOCK_RESERVATION_REPOSITORY",
);
export const STOCK_RELEASE_UNIT_OF_WORK = Symbol("STOCK_RELEASE_UNIT_OF_WORK");
